services:
  redis:
    extends:
      file: docker-partials/redis.yml
      service: redis

  redis-insight:
    extends:
      file: docker-partials/redis-insight.yml
      service: redis-insight

  caddy:
    extends:
      file: docker-partials/caddy.yml
      service: caddy

  n8n-main:
    extends:
      file: docker-partials/n8n-main.yml
      service: n8n-main

  n8n-worker:
    extends:
      file: docker-partials/n8n-worker.yml
      service: n8n-worker
    deploy:
      replicas: 3

  postgres:
    extends:
      file: docker-partials/postgres.yml
      service: postgres

  qdrant:
    extends:
      file: docker-partials/qdrant.yml
      service: qdrant

volumes:
  caddy_data:
  n8n_data:
  postgres_storage:
  qdrant_storage:
  redis_storage:

networks:
  n8n-network:
    driver: bridge
