services:
  redis:
    extends:
      file: docker-partials/redis.yml
      service: redis

  redis-insight:
    extends:
      file: docker-partials/redis-insight.yml
      service: redis-insight

  caddy:
    extends:
      file: docker-partials/caddy.yml
      service: caddy
    depends_on:
      - postgres
      - redis
      - qdrant

  n8n:
    extends:
      file: docker-partials/n8n.yml
      service: n8n

  postgres:
    extends:
      file: docker-partials/postgres.yml
      service: postgres

  qdrant:
    extends:
      file: docker-partials/qdrant.yml
      service: qdrant

volumes:
  caddy_data:
  postgres_storage:
  qdrant_storage:
  redis_storage:

networks:
  n8n-network:
    driver: bridge
