services:
  caddy:
    extends:
      file: docker-partials/caddy.yml
      service: caddy

  n8n:
    extends:
      file: docker-partials/n8n.yml
      service: n8n

  postgres:
    extends:
      file: docker-partials/postgres.yml
      service: postgres

volumes:
  caddy_data:
    external: true
  n8n_data:
    external: true
  postgres_storage:
    external: true

networks:
  n8n-network:
    driver: bridge
