services:
  redis:
    extends:
      file: docker-partials/redis.yml
      service: redis

  redis-insight:
    extends:
      file: docker-partials/redis-insight.yml
      service: redis-insight

  caddy:
    extends:
      file: docker-partials/caddy.yml
      service: caddy

  n8n:
    extends:
      file: docker-partials/n8n.yml
      service: n8n

  postgres:
    extends:
      file: docker-partials/postgres.yml
      service: postgres

  qdrant:
    extends:
      file: docker-partials/qdrant.yml
      service: qdrant

  ollama:
    extends:
      file: docker-partials/ollama.yml
      service: ollama

  jina-embeddings:
    extends:
      file: docker-partials/jina-embeddings.yml
      service: jina-embeddings

volumes:
  caddy_data:
  n8n_data:
  ollama_data:
  postgres_storage:
  qdrant_storage:
  redis_storage:

networks:
  n8n-network:
    driver: bridge
