services:
  n8n:
    extends:
      file: docker-partials/n8n.yml
      service: n8n
    env_file: .env
    volumes:
      - ./config/do_ca.crt:/etc/ssl/certs/do_ca.crt:ro


  caddy:
    extends:
      file: docker-partials/caddy.yml
      service: caddy
    env_file: .env
    depends_on:
      n8n:
        condition: service_healthy

  qdrant:
    extends:
      file: docker-partials/qdrant.yml
      service: qdrant
    env_file: .env

volumes:
  caddy_data:
  n8n_data:
  qdrant_storage:

networks:
  n8n-network:
    driver: bridge
