services:
  caddy:
    container_name: caddy
    image: caddy:2.9.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../data/caddy/data:/data
      - ../data/caddy/config:/config
      - ../config/caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - n8n-network
