services:
  init-qdrant:
    image: curlimages/curl:8.8.0       # dispone de curl completo
    container_name: init-qdrant
    depends_on:
      - qdrant
    networks: ["n8n-network"]
    environment:
      - QDRANT_API_KEY=${QDRANT__SERVICE__API_KEY}
      - QDRANT_HOST=http://qdrant:6333  # nombre del servicio interno
    entrypoint: >
      sh -c '
        echo "🔄 Esperando a Qdrant…";
        until curl -sf "$QDRANT_HOST/healthz"; do sleep 1; done;
        echo "✅ Qdrant está activo.";
        
        if curl -s -H "api-key: $QDRANT_API_KEY" \
               "$QDRANT_HOST/collections/faq" \
               | grep -q "\"status\":\"ok\""; then
          echo "ℹ️  La colección faq ya existe. Nada que hacer.";
          exit 0;
        fi;
        
        echo "🚀 Creando colección faq (1536 dimensiones, distancia Dot)…";
        curl -s -X PUT "$QDRANT_HOST/collections/faq" \
             -H "Content-Type: application/json" \
             -H "api-key: $QDRANT_API_KEY" \
             -d "{\"vectors\": {\"size\": 1536, \"distance\": \"Dot\"}}";
        echo "✅ Colección faq creada.";
      '
    restart: "no"    # solo se ejecuta una vez
