services:
  n8n-main:
      container_name: n8n
      image: docker.n8n.io/n8nio/n8n:latest
      restart: always
      expose:
        - 5678
      environment:
        - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
        - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
        - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
        - DB_POSTGRESDB_USER=${POSTGRES_USER}
        - DB_TYPE=${DB_TYPE}
        - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
        - N8N_DIAGNOSTICS_ENABLED=false
        - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
        - N8N_PERSONALIZATION_ENABLED=false
        - N8N_RUNNERS_ENABLED=true
        - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET}
        - QUEUE_BULL_REDIS_HOST=${REDIS_HOST}
        - QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}
        - QUEUE_BULL_REDIS_PORT=${REDIS_PORT}
        - TZ=${TZ}
        - WEBHOOK_URL=${WEBHOOK_URL}
        - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
        - N8N_LOG_LEVEL=debug
        - N8N_PAYLOAD_SIZE_MAX=64m
        - NODE_OPTIONS=--max_old_space_size=3072
        - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=none
        - EXECUTIONS_DATA_SAVE_ON_SUCCESS=false
        - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
        - EXECUTIONS_MODE=queue
        - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS="true"
        - QUEUE_HEALTH_CHECK_ACTIVE="true"
      volumes:
        - n8n_data:/home/node/.n8n
        - ${DATA_FOLDER}/local_files:/files
        - ../.env:/files/.env
      networks:
        - n8n-network
      healthcheck:
        test: ["CMD-SHELL", "pgrep node"]
        interval: 30s
        timeout: 5s
        retries: 3
