services:
  n8n-worker:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    depends_on:
      - redis
      - postgres
    environment:
      # --- base de datos ---
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}

      # --- cola BullMQ ---
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=${REDIS_HOST}
      - QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}
      - QUEUE_BULL_REDIS_PORT=${REDIS_PORT}

      # --- cifrado & task-runners ---
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true

      # --- desactivar UI ---
      - N8N_DISABLE_UI=true
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true

      # housekeeping / varios
      - TZ=${TZ}
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

      - QUEUE_BULL_REDIS_DB=0
      - QUEUE_BULL_REDIS_PREFIX=bull

    networks:
      - n8n-network
    healthcheck:
      test: ["CMD-SHELL", "pgrep node"]
      interval: 30s
      timeout: 5s
      retries: 3
