services:
  n8n:
      container_name: n8n
      image: docker.n8n.io/n8nio/n8n:latest
      restart: always
      expose:
        - 5678
      healthcheck:
        test: ["CMD-SHELL", "pgrep node"]
        interval: 30s
        timeout: 5s
        retries: 3
