services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    networks: ["n8n-network"]
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
    volumes:
      - ollama_data:/data
