services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    networks: ["n8n-network"]
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
      - ./postgresql.conf:/tmp/postgresql.conf
      - ./pg_hba.conf:/tmp/pg_hba.conf
    command: >
      bash -c "
        cp /tmp/postgresql.conf /var/lib/postgresql/data/postgresql.conf &&
        cp /tmp/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf &&
        chown postgres:postgres /var/lib/postgresql/data/*.conf &&
        exec docker-entrypoint.sh postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
