services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    networks: ["n8n-network"]
    restart: unless-stopped
    ports:
      - 6333:6333
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT__SERVICE__API_KEY}
    volumes:
      - ../data/qdrant:/qdrant/storage
