services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks: ["n8n-network"]
    ports:
      - 6379:6379
    volumes:
      - redis_storage:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
