services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks: ["n8n-network"]
    expose:
      - 6379
    volumes:
      - redis_storage:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
